import express, { Request, Response } from 'express';
import checkCookieExpiration from '../middleware/cookiesMiddleware';
import roomController from '../controller/roomController';
const room = express.Router();
room.use(checkCookieExpiration);
room.post('/', roomController.generateRoom);
room.get('/', roomController.getRooms);
room.get('/archived', roomController.getArchivedRooms);
room.post('/participants/:id', roomController.joinRoom);
room.get('/participants/:id', roomController.getParticipants);
room.get('/:user_id', roomController.getJoinedRooms);
export default room;
