import express, { Request, Response } from 'express';
import checkCookieExpiration from '../middleware/cookiesMiddleware';
import roomController from '../controller/roomController';
const room = express.Router();
room.use(checkCookieExpiration);
room.post('/', roomController.generateRoom);
room.get('/', roomController.getRooms);
room.get('/archived', roomController.getArchivedRooms);
room.post('/participants', roomController.joinRoom);
room.get('/participants', roomController.getParticipants);
room.get('/user', roomController.getJoinedRooms);
export default room;
